import express from "express";
import { RegisterEtu,LoginEtu,LogoutEtu,getAllAffichesStudent,getOneAfficheStudents,getNomDepClass,getEmploiStudent,getOneEmploiStudent,DownolodsFile,addDocumentForStudent,DeleteDocumentStudent,DocumentOneStudent,addMessageStudent} from "../controllers/Etudiants.js";
import { RegisterChef,LoginChef,LogoutChef,getNomDep,MessageChefDep} from "../controllers/ChefDep.js";
import { LoginAdmin,RegisterAdmin,LogoutAdmin, AddCarteEtu,AddChefAutorization,AddAdminAutorization,getChefUsers,getStudentUsers,getChefUserById,getStudentUserById,updateChefUser,updateStudentUser,deleteChefUser,deleteStudentUser} from "../controllers/Admin.js";
import { verifyToken } from "../middleware/VerifyToken.js";
import { refreshTokenChef, refreshTokenEtu, refreshTokenAdmin} from "../controllers/RefreshToken.js";
import { addAffiche,getAllAffiches,getAllDocument,getOneAffiche,updateAffiche,deleteAffiche,deleteDocument,getPublishedAffiche,upload,DocumentForAdmin} from "../controllers/AfficheController.js";
import {addAfficheChef, uploadChef,getAllAffichesChef,getOneAfficheChef,updateAfficheChef,deleteAfficheChef,addEmploi,getAllEmplois,getOneEmploi,updateEmploiChef,deleteEmploiChef } from "../controllers/ChefAffich.js"


const router = express.Router();

router.post('/RegisterEtu', RegisterEtu);
router.post('/RegisterChef', RegisterChef);
router.post('/RegisterAdmin', RegisterAdmin);
router.post('/LoginEtu', LoginEtu);
router.post('/LoginAdmin', LoginAdmin);
router.post('/LoginChef', LoginChef);
router.get('/tokenEtu', refreshTokenEtu);
router.get('/tokenChef', refreshTokenChef);
router.get('/tokenAdmin', refreshTokenAdmin);
router.delete('/logoutEtu', LogoutEtu);
router.delete('/LogoutChef', LogoutChef);
router.delete('/LogoutAdmin', LogoutAdmin);
router.post('/addAffiche' , upload , addAffiche);
router.get('/allDocument', getAllDocument );
router.get('/ChefUsers',getChefUsers);
router.get('/StudentUsers',getStudentUsers);
router.get('/allAffiches',verifyToken, getAllAffiches );
router.get('/published', getPublishedAffiche);
router.get('/:id', getOneAffiche);
router.put('/:id', updateAffiche);
router.delete('/:id', deleteAffiche);
router.delete('/deleteDocument/:id',deleteDocument);
router.post('/AddCarteEtu', AddCarteEtu);
router.post('/AddChefAutorization', AddChefAutorization );
router.post('/AddAdminAutorization', AddAdminAutorization );
router.post('/addAfficheChef' , uploadChef, addAfficheChef);
router.get('/allAffichesChef/:nom_dep', getAllAffichesChef );
router.get('/AfficheChef/:id', getOneAfficheChef);
router.put('/AfficheChef/edit/:id', updateAfficheChef);
router.delete('/AfficheChef/:id', deleteAfficheChef);
router.get('/getNomDep/:name',getNomDep);
router.post('/addMessageChef',MessageChefDep);
router.post('/addEmploi' , uploadChef, addEmploi);
router.get('/allEmploisChef/:nom_dep', getAllEmplois );
router.get('/EmploiChef/:id', getOneEmploi);
router.put('/EmploiChef/edit/:id', updateEmploiChef);
router.delete('/EmploiChef/:id', deleteEmploiChef);
router.get ('/allAffichesStudent/:nom_dep/:ClasseStudent', getAllAffichesStudent );
router.get('/AfficheStudent/:id',getOneAfficheStudents);
router.get('/getNomDepClass/:name', getNomDepClass);
router.get ('/getEmploiStudent/:nom_dep/:ClasseStudent', getEmploiStudent );
router.get('/EmploiStudent/:id', getOneEmploiStudent);
router.get('/DownolodsFile/:file', DownolodsFile);
router.post('/addDocumentStudent', upload,addDocumentForStudent);
router.delete('/deleteDocumentStudent/:id', DeleteDocumentStudent);
router.get('/getDocumentOneStudent/:name', DocumentOneStudent );
router.post('/addMessageStudent', addMessageStudent);
router.post('/addDocumentAdmin', upload, DocumentForAdmin);
router.get('/ChefUsers/:id', getChefUserById);
router.patch('/ChefUsers/:id', updateChefUser);
router.delete('/ChefUsers/:id',deleteChefUser);
router.get('/StudentUsers',getStudentUsers);
router.get('/StudentUsers/:id', getStudentUserById);
router.patch('/StudentUsers/:id', updateStudentUser);
router.delete('/StudentUsers/:id',deleteStudentUser);


export default router;